WCSCoavBundle\Entity\Flight:
    type: entity
    table: null
    repositoryClass: WCSCoavBundle\Repository\FlightRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        pilot:
            type: string
            length: '255'
        freeSeats:
            type: integer
        takeofTime:
            type: datetime
    lifecycleCallbacks: {  }

    manyToOne:
        departure:
            targetEntity: WCSCoavBundle\Entity\Terrain
            inversedBy: departures

        arrival:
            targetEntity: WCSCoavBundle\Entity\Terrain

        plane:
            targetEntity: PlaneModel

    oneToMany:
        reservations:
            targetEntity: WCSCoavBundle\Entity\Reservation
            mappedBy: flight